default: &default
  url: redis://localhost:6379
  db: 0
  driver: hiredis

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
  url: <%= Rails.application.credentials.fetch("redis_url") { "redis://localhost:6379/1" } %>
