module Constants
  module Room
    PUBLIC_MAX_COUNT = 3
    PRIVATE_MAX_COUNT = 3
    COUNTDOWN_CHOOSE_WORD = 15
    COUNTDOWN_DRAW = 90
    COUNTDOWN_ROUND_OVER = 5
    MAX_CHAT_MESSAGE_SIZE = 50

    PAINTER_SCORE_ON_GUESS_RIGHT = 10
  end
end